from start import STATS, save_stats

STATS["BULLET DAMAGE"] = 1
#STATS["BULLET KNOCKBACK"] = 50
STATS["BULLET FREQUENCY"] = 10
STATS['BULLET SPEED'] = 7
STATS["TURRET LEVEL"] = 1
STATS["BEAM WIDTH"] = 15
STATS["LIGHTHOUSE HP"] = 2

save_stats(STATS)